'------------------------------------------------------------------------------
' <auto-generated>
'     이 코드는 도구를 사용하여 생성되었습니다.
'     런타임 버전:4.0.30319.1
'
'     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
'     이러한 변경 내용이 손실됩니다.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    '클래스에서 자동으로 생성되었습니다.
    '멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    '다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    '''<summary>
    '''  지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PackofProginner.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        '''  속성을 재정의합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property actbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("actbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property askbut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("askbut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backbut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backbut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_al() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_al", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_ask1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_ask1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_code() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_code", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_stydy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_stydy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_title() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_title", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_tut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_tut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property codebut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("codebut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dimbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dimbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ex_mf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ex_mf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property imgerror() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("imgerror", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property jobar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jobar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loadbut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loadbut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loadbut1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loadbut1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loadbut2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loadbut2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loadbut3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loadbut3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property next100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property next70() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next70", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property playbut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("playbut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property prev100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prev100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property prev70() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prev70", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property savebut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("savebut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property setbut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("setbut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property silbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sndpause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sndpause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sndplay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sndplay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sndstop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sndstop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property st_alg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("st_alg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property st_bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("st_bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property st_exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("st_exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property st_pro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("st_pro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stopbut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stopbut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property undobut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("undobut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
